### ISSUE TITLE
Merge with ncursesw?

### ISSUE THREAD

**Issue by gauteh** [ruby/curses#2]
Hi,

I am currently the maintainer of the ncursesw gem (https://rubygems.org/gems/ncursesw, originally based on the seemingly unmaintained: http://ncurses-ruby.berlios.de/) which we host as part of the sup-heliotrope project: https://github.com/sup-heliotrope/ncursesw-ruby.

It seems that this project is overlapping, but I think that our implementation is slightly more extensive. Would it be worth the effort to join the projects?

Complement issue: https://github.com/sup-heliotrope/ncursesw-ruby/issues/22

Regards, Gaute

**Comment by shugo** [comment]
Hello, I'm the original author of this binding.

ncursesw looks feature rich but it has a different concept from this project,
so I'd like to maintain this project for my own use rather than closing.

@drbrain Could you add me to the owners of this gem if you don't have enough time for this project?

**Comment by drbrain** [comment]
You are now an owner, @shugo

 https://rubygems.org/gems/curses

**Comment by shugo** [comment]
@drbrain Thank you!
